---
title: "arg2"
---
```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
SEARCHLIMIT <- 50
SIMREPETITIONS <- 1000
```

```{r cache=TRUE}
simulation <- function(freq_arms = .5, freq_legs = .5) {
  
  
  reveal_or_decide <- function() {       # FF: focused feature
    if ( is.na(slots[focused_feature])) { # is the slot with the FF still empty?
      if ( card[paste0(focused_feature, "visible")] ) {   # is the FF already visible?
        
        # placement decision:
        if (card[paste0(focused_feature, "value")] == 'long') { # is the FF long?
          
          slots[focused_feature] <<- card # place this card in slot
          # note: this assumes kids don't re-decide on the slot upon seeing card!
        }
        
      } else { # if FF is still covered:
        ## query the focused_feature => reveal it
        card[paste0(focused_feature, "visible")] <<- TRUE
        queries <<- queries + 1
        reveal_or_decide()
      }
    }
  }
  
  ## STARTS HERE
  ## -----------
  queries <- 0
  slots <- list(A = NA, B = NA) # the slots entity
  population <- tribble(
    ~card, ~Avalue, ~Bvalue, ~Avisible, ~Bvisible,
    1,  "long", "long",   F, F,
    2,  "long", "short",  F, F,
    3,  "short", "long",  F, F,
    4,  "short", "short", F, F,
    5,  "short", "long",  F, F,
    6,  "short", "short", F, F,
    7,  "short", "long",  F, F,
    8,  "short", "short", F, F,
    9,  "short", "long",  F, F,
    10, "short", "short", F, F
  )

  while ((is.na(slots$A) || is.na(slots$B)) && length(population) > 0) {
    
    ## draw a monster card:
    rnd <- sample(1:nrow(population), size = 1)
    card <- population[rnd,]
    population <- population[-rnd,]
    
    # in what order kids try to fill the slots -- for now, set something simple
    # (but this is a relevant simulation target later with manip. frequencies!)
    focused_feature_sequence <- sample(c('A', 'B'))
    focused_feature <- focused_feature_sequence[1]
    reveal_or_decide()
    focused_feature <- focused_feature_sequence[2]
    reveal_or_decide()
  }
  
  tibble(queries = queries,
         A = slots$A,
         B = slots$B)

}
```

```{r cache=TRUE}
freqrange_arms <- seq(.05, .95, by = .05)
freqrange_legs <- seq(.05, .95, by = .05)
freqrange <- list(freq_arms = freqrange_arms, freq_legs = freqrange_legs) %>% 
  cross_df()
#    arms  legs
#   <dbl> <dbl>
#    0.05  0.05
#    0.1   0.05
#    0.15  0.05
#      [...]
#    0.85  0.95
#    0.9   0.95
#    0.95  0.95

sims <- replicate(SIMREPETITIONS,
                  as.numeric( pmap( freqrange, simulation ) ) ) %>%
  as_tibble(.name_repair = "unique")

sims$freq_arms <- freqrange$freq_arms
sims$freq_legs <- freqrange$freq_legs
# arms legs  sim1 sim2 ... simSIMREPETITIONS
#  .05  .05     .    .           .
#  .05  .10     .    .           .
#  ...
#  .95  .90     .    .           .
#  .95  .95     .    .           .

# reshape this tibble for plotting:
simplot <- sims %>% 
  pivot_longer(cols = -c(freq_arms, freq_legs)) %>% 
  select(-name)

ggplot(simplot,
       aes(x = value)) +
  geom_histogram(binwidth = 1) +
  facet_grid(freq_arms ~ freq_legs) +
  xlim(c(0, 50))
ggsave("361 histograms.pdf", height = 30, width = 49, units = "in")
```


