---
title: "arg2"
---
```{r setup, include=FALSE}
library(tidyverse)
library(memoise)
library(patchwork)
colscale <- scale_fill_manual(values = c(
  # 3 red tones
  "#990000",
  "#bb2222",
  "#dd4444",
  # 3 yellow tones
  "#999900",
  "#bbbb22",
  "#dddd44",
  # 1 green tone
  "#22bb00"
))
```

```{r general functions}
normalize <- function(x) {
  if (sum(x)==0) x else x/sum(x)
}
```

```{r functions}
agent_choose <- function(state, parameters, force_new) {

  ## enforcing 'new'? Skip all further decisions:
  if( force_new ) return("new")
  
  
  
  actions_excel <- lookup_state_in_excel_file_memoized(state)
  errors <- c("E", "RR", "RR/2", "r", "r/2", "P")
  ## vector of actions that are ok according to the excel sheet:
  ok_opts <- actions_excel %>% select( which(actions_excel == "ok") ) %>% names
  ## vector of available errors (parameter names, not action names!):
  error_opts <- actions_excel %>% select( which(actions_excel %in% errors) )
  
  
  
  ## no errors available? choose the one ok option or toss coin between two:
  if( length(error_opts) == 0 ) return( sample(ok_opts, 1) )
  
  
  
  ## one error available? allow it to happen or choose ok action(s):
  if( length(error_opts) == 1 ){
    
    ## identify relevant parameter for this option:
    relevant_parameters <- ifelse(
      error_opts %in% c("RR", "RR/2", "r", "r/2"), "R", error_opts) %>%
      unlist
      
    ## does the error happen? then return it
    if( parameters[[relevant_parameters]] > runif(1) ) {
      return( names(error_opts) )
    } else {
      ## otherwise return (one of) ok opt:
      return( sample(ok_opts, 1) )
    }
  }
  
  
  
  ## two errors available? allow both, resolve ties:
  if( length(error_opts) == 2 ){
    ## 1-2 out of E, R, P:
    relevant_parameters <- ifelse(
      error_opts %in% c("RR", "RR/2", "r", "r/2"), "R", error_opts
    ) %>% unlist
    
    ## shuffle to allow 1 or 2 errors:
    error1 <- parameters[[ relevant_parameters[1] ]] > runif(1)
    error2 <- parameters[[ relevant_parameters[2] ]] > runif(1)
    
    ## process the result:
    if( error1 + error2 == 0 ) final_action <- ok_opts # may need to change this if >1 become possible
    if( error1 + error2 == 1 ) final_action <- error_opts[c(error1, error2)] %>% names
    if( error1 + error2 == 2 ) {
      ## both errors occurred? resolve tie by scaling Ps to 1 for decision:
      p1_prime <- normalize( c(parameters[[ relevant_parameters[1] ]],
                               parameters[[ relevant_parameters[2] ]]) )[1]
      p2_prime <- 1 - p1_prime
      final_action <- sample(c(error_opts[1], error_opts[2]),
                             1, F, c(p1_prime, p2_prime)) %>% 
        names
    }
    return(final_action)
  }
  
  ## how did you get here?
  browser()
}



lookup_state_in_excel_file <- function(state) {
  ## compress state into single string representation
  state_chr <- state %>%
    mutate(slot = ifelse(slot == "[   ]", "[   ]", "full")) %>% 
    state_wider %>%
    unlist %>%
    as.character %>%
    paste0(collapse = ' ')
  
  ## load excel table with states and actions
  xlsx <- readxl::read_excel('states and actions.xlsx', skip = 2)
  all_states_chr <- xlsx %>% select(rare:featB) %>%
    apply(1, paste0, collapse = ' ')
  
  ## cough if current state is not in any of the rows in Excel sheet:
  if (sum(state_chr == all_states_chr) != 1) browser()
  stopifnot(sum(state_chr == all_states_chr) == 1)
  
  ## identify actions that correspond to state
  actions <- xlsx[state_chr == all_states_chr,] %>% select(new:assB)
  stopifnot(nrow(actions) == 1)
  stopifnot(isTRUE(all.equal(colnames(actions), c("new", "qA", "qB", "assA", "assB"))))
  actions
}



lookup_state_in_excel_file_memoized <- memoise::memoize(lookup_state_in_excel_file)
state_wider <- function(state) {
  state %>% pivot_wider(names_from = feature, values_from = c(slot, card))
}



simulation <- function(population, parameters, rare_feature) {
  
  game_execute_action <- function(chosen_action) {
    ## given the current state and the agent's selection of one action, execute
    ## action and update the global variable representing the game state
    
    ## this function works with side effects / global assignments / <<-
    if (chosen_action == 'new') {
      ## sample next card
      card <<- population %>% filter(card == card_sequence[card_sequence_index])
      card_sequence_index <<- card_sequence_index + 1
      ## reset state
      state[state$feature == 'A',]$card <<- 'x'
      state[state$feature == 'B',]$card <<- 'x'
    } else if (chosen_action == 'qA') {
      state[state$feature == 'A',]$card <<- card[card$feature == 'A',]$value
    } else if (chosen_action == 'qB') {
      state[state$feature == 'B',]$card <<- card[card$feature == 'B',]$value
    } else if (chosen_action == 'assA') {
      state[state$feature == 'A',]$slot <<- state[state$feature == "A",]$card
    } else if (chosen_action == 'assB') {
      state[state$feature == 'B',]$slot <<- state[state$feature == "B",]$card
    }
  }
  
  
  
  update_history <- function() {
    history_row <- bind_cols(
      i = i, 
      state %>% state_wider, 
      #actions,
      chosen_action = chosen_action, 
      card %>% pivot_wider(names_from = feature, values_from = value))
    history[[i]] <<- history_row
  }
  
  
  
  state <- tribble(
    ~rare, ~feature, ~slot, ~card,
    rare_feature, 'A', '[   ]', 'x',
    rare_feature, 'B', '[   ]', 'x'
  )
  
  card_sequence <- sample(1:max(population$card))
  card_sequence_index <- 1
  
  ## initialize game
  
  ## apparently faster to fill list than creating copies with new entries each
  ## time:
  history <- list(rep(NA, 100)) 
  force_new <- TRUE
  record_slotA <- ''
  record_slotB <- ''
  
  ## play game
  for (i in 1:100) {
    #actions <- disable_invalid_actions()
    #actions <- agent_update_actions(actions, state, parameters)
    #if (!(any(actions > 0))) browser()
    chosen_action <- agent_choose(state, parameters, force_new)
    if (chosen_action == 'new') {
      if (card_sequence_index > length(card_sequence)) break  ## game over
    }
    game_execute_action(chosen_action)
    
    if (chosen_action == 'assA') {
      record_slotA <- state$card[state$feature == 'A']
    }
    if (chosen_action == 'assB') {
      record_slotB <- state$card[state$feature == 'B']
    }
    
    update_history()
    
    force_new <- chosen_action %in% c('assA', 'assB')
    if ( !("[   ]" %in% state$slot) )  {
      break  ## game over
    }
  }
  
  ## update progress bar:
  #pb$tick()$print()
  
  ## result: the whole log
  history %>% 
    keep(function(x) length(x) > 1) %>% # remove empty entries
    bind_rows
}
```

Run the simulation: set one or more dimensions on which we vary parameters, feed them to the simulation, get a resulting data structure for later analysis.

```{r run, cache=TRUE}
## set parameter ranges and other initial values:
set.seed(123)
RUNS <- 5 # 1000 runs: ca. 10h runtime (Andreas, 20191209)

## init actor's parameters on (E)fficiency, (R)isk and comprehension of
## (P)lacement rules:
PARAMETERS <- list()
PARAMETERS$E <- .2
PARAMETERS$R <- .3
PARAMETERS$P <- .05

## the card stack with which we start the simulation:
POP_SKEWED_SMALL <- tribble(~card, ~A, ~B,
                            1,  'long',  'long',
                            2,  'long',  'long',
                            3,  'long',  'short',
                            4,  'short', 'long',
                            5,  'short', 'long',
                            6,  'short', 'long',
                            7,  'short', 'long',
                            8,  'short', 'long',
                            9,  'short', 'long',
                            10, 'short', 'short',
                            11, 'short', 'short',
                            12, 'short', 'short',
                            13, 'short', 'short',
                            14, 'short', 'short',
                            15, 'short', 'short'
) %>% pivot_longer(A:B, names_to = 'feature', values_to = 'value')

POP_EVEN_SMALL <- tribble(~card, ~A, ~B,
                          1,  'long',  'long',
                          2,  'long',  'long',
                          3,  'long',  'long',
                          4,  'long',  'long',
                          5,  'long',  'short',
                          6,  'long',  'short',
                          7,  'long',  'short',
                          8,  'long',  'short',
                          9,  'short', 'long',
                          10, 'short', 'long',
                          11, 'short', 'long',
                          12, 'short', 'long',
                          13, 'short', 'short',
                          14, 'short', 'short',
                          15, 'short', 'short',
                          16, 'short', 'short'
) %>% pivot_longer(A:B, names_to = 'feature', values_to = 'value')

POP_SKEWED_LARGE <- tribble(~card, ~A, ~B,
                      1, 'long', 'long',
                      2, 'long', 'long',
                      3, 'long', 'short',
                      4, 'short', 'long',
                      5, 'short', 'long',
                      6, 'short', 'long',
                      7, 'short', 'long',
                      8, 'short', 'long',
                      9, 'short', 'long',
                      10, 'short', 'long',
                      11, 'short', 'long',
                      12, 'short', 'long',
                      13, 'short', 'long',
                      14, 'short', 'short',
                      15, 'short', 'short',
                      16, 'short', 'short',
                      17, 'short', 'short',
                      18, 'short', 'short',
                      19, 'short', 'short',
                      20, 'short', 'short',
                      21, 'short', 'short',
                      22, 'short', 'short',
                      23, 'short', 'short'
) %>% pivot_longer(A:B, names_to = 'feature', values_to = 'value')

POP_EVEN_LARGE <- tribble(~card, ~A, ~B,
                    1,  'long', 'long',
                    2,  'long', 'long',
                    3,  'long', 'long',
                    4,  'long', 'long',
                    5,  'long', 'short',
                    6,  'long', 'short',
                    7,  'long', 'short',
                    8,  'long', 'short',
                    9,  'short', 'long',
                    10, 'short', 'long',
                    11, 'short', 'long',
                    12, 'short', 'long',
                    13, 'short', 'short',
                    14, 'short', 'short',
                    15, 'short', 'short',
                    16, 'short', 'short',
                    17,  'long', 'long',
                    18,  'long', 'long',
                    19,  'long', 'short',
                    20,  'long', 'short',
                    21, 'short', 'long',
                    22, 'short', 'long',
                    23, 'short', 'short',
                    24, 'short', 'short'
) %>% pivot_longer(A:B, names_to = 'feature', values_to = 'value')


## what we vary to simulate a range of setups:
## How frequently does the agent commit an error of a certain kind?
##                 +--never commit this error
##                 |   +---max.
##                 |   |
##                 V   V
TESTRANGE_E <- seq(0,  0.5, length.out = 6)
TESTRANGE_R <- seq(0,  0.5, length.out = 6)
TESTRANGE_P <- seq(0,  0.1, length.out = 3)



## build list of parameter variations to feed into the simulation:
sim_params <- expand.grid(
  run = 1:RUNS,
  error_E = TESTRANGE_E,
  error_R = TESTRANGE_R,
  error_P = TESTRANGE_P
) %>% as.list



## Spread the simulation on our grid of parameter ranges. raw output is a tbl
## of histories of every run:
simulate_range <- function(params, card_deck, rare_feature){
  out_raw_skewed_large <- pmap(params,
                               function(run, error_E, error_R, error_P) {
                                 if( run %% RUNS == 0) cat(".")
                                 PARAMETERS$E <- error_E
                                 PARAMETERS$R <- error_R
                                 PARAMETERS$P <- error_P
                                 simulation(population = card_deck,
                                            parameters = PARAMETERS,
                                            rare_feature = "A") %>%
                                   mutate(param_E = error_E,
                                          param_R = error_R,
                                          param_P = error_P,
                                          run = run)
                               }) %>% 
    bind_rows
}

## run the range-wise simulation for card decks large and small, even and
## skewed:
cat("\ncard set 1/4...\n")
out_raw_skewed_large <- simulate_range(sim_params, POP_SKEWED_LARGE, "A")
cat("card set 2/4...\n")
out_raw_even_large   <- simulate_range(sim_params, POP_EVEN_LARGE, "none")
cat("card set 3/4...\n")
out_raw_skewed_small <- simulate_range(sim_params, POP_SKEWED_SMALL, "A")
cat("card set 4/4...\n")
out_raw_even_small   <- simulate_range(sim_params, POP_EVEN_SMALL, "none")

## save copy of the simulation dataset for safety:
write.table("rdata/simulation_data.RData")
```

Analyses:

```{r}
# How often did both slots get filled with a long feature?
outcomes_skewed_large <- out_raw_skewed_large %>% 
  group_by( param_E, param_R, param_P, run ) %>% 
  filter( i == max(i) ) %>% 
  ungroup %>% 
  group_by( param_E, param_R, param_P ) %>% 
  summarize( both_long    = sum( slot_A == "long"  & slot_B == "long" ),
             only_A_long  = sum( slot_A == "long"  & slot_B == "short" ),
             only_B_long  = sum( slot_A == "short" & slot_B == "long" ),
             both_short   = sum( slot_A == "short" & slot_B == "short" ),
             A_missing    = sum( slot_A == "[   ]" & slot_B %in% c("long", "short") ),
             B_missing    = sum( slot_A %in% c("long", "short") & slot_B == "[   ]" ),
             both_missing = sum( slot_A == "[   ]" & slot_B == "[   ]" )
  ) %>% ungroup

outcomes_even_large <- out_raw_even_large %>% 
  group_by( param_E, param_R, param_P, run ) %>% 
  filter( i == max(i) ) %>% 
  ungroup %>% 
  group_by( param_E, param_R, param_P ) %>% 
  summarize( both_long    = sum( slot_A == "long"  & slot_B == "long" ),
             only_A_long  = sum( slot_A == "long"  & slot_B == "short" ),
             only_B_long  = sum( slot_A == "short" & slot_B == "long" ),
             both_short   = sum( slot_A == "short" & slot_B == "short" ),
             A_missing    = sum( slot_A == "[   ]" & slot_B %in% c("long", "short") ),
             B_missing    = sum( slot_A %in% c("long", "short") & slot_B == "[   ]" ),
             both_missing = sum( slot_A == "[   ]" & slot_B == "[   ]" )
  ) %>% ungroup

outcomes_skewed_small <- out_raw_skewed_small %>% 
  group_by( param_E, param_R, param_P, run ) %>% 
  filter( i == max(i) ) %>% 
  ungroup %>% 
  group_by( param_E, param_R, param_P ) %>% 
  summarize( both_long    = sum( slot_A == "long"  & slot_B == "long" ),
             only_A_long  = sum( slot_A == "long"  & slot_B == "short" ),
             only_B_long  = sum( slot_A == "short" & slot_B == "long" ),
             both_short   = sum( slot_A == "short" & slot_B == "short" ),
             A_missing    = sum( slot_A == "[   ]" & slot_B %in% c("long", "short") ),
             B_missing    = sum( slot_A %in% c("long", "short") & slot_B == "[   ]" ),
             both_missing = sum( slot_A == "[   ]" & slot_B == "[   ]" )
  ) %>% ungroup

outcomes_even_small <- out_raw_even_small %>% 
  group_by( param_E, param_R, param_P, run ) %>% 
  filter( i == max(i) ) %>% 
  ungroup %>% 
  group_by( param_E, param_R, param_P ) %>% 
  summarize( both_long    = sum( slot_A == "long"  & slot_B == "long" ),
             only_A_long  = sum( slot_A == "long"  & slot_B == "short" ),
             only_B_long  = sum( slot_A == "short" & slot_B == "long" ),
             both_short   = sum( slot_A == "short" & slot_B == "short" ),
             A_missing    = sum( slot_A == "[   ]" & slot_B %in% c("long", "short") ),
             B_missing    = sum( slot_A %in% c("long", "short") & slot_B == "[   ]" ),
             both_missing = sum( slot_A == "[   ]" & slot_B == "[   ]" )
  ) %>% ungroup
```

```{r plot_outcome}
plot_skewed_small <- outcomes_skewed_small %>% 
  pivot_longer( both_long:both_missing,
                names_to = "outcome",
                values_to = "count" ) %>% 
  mutate( outcome = fct_relevel(outcome,
                                "both_missing",
                                "B_missing",
                                "A_missing",
                                "both_short",
                                "only_B_long",
                                "only_A_long",
                                "both_long"
  )) %>% 
  ggplot(aes( x = param_E,
              y = count,
              fill = outcome )) +
  geom_area() +
  colscale +
  facet_grid(param_P ~ param_R, labeller = label_both) +
  ggtitle("skewed (rare feature A), 15 cards")





plot_even_small <- outcomes_even_small %>% 
  pivot_longer( both_long:both_missing,
                names_to = "outcome",
                values_to = "count" ) %>% 
  mutate( outcome = fct_relevel(outcome,
                                "both_missing",
                                "B_missing",
                                "A_missing",
                                "both_short",
                                "only_B_long",
                                "only_A_long",
                                "both_long"
  )) %>% 
  ggplot(aes( x = param_E,
              y = count,
              fill = outcome )) +
  geom_area() +
  guides(fill = F) +
  colscale +
  facet_grid(param_P ~ param_R, labeller = label_both) +
  ggtitle("even pop., 16 cards")





plot_skewed_large <- outcomes_skewed_large %>% 
  pivot_longer( both_long:both_missing,
                names_to = "outcome",
                values_to = "count" ) %>% 
  mutate( outcome = fct_relevel(outcome,
                                "both_missing",
                                "B_missing",
                                "A_missing",
                                "both_short",
                                "only_B_long",
                                "only_A_long",
                                "both_long"
  )) %>% 
  ggplot(aes( x = param_E,
              y = count,
              fill = outcome )) +
  geom_area() +
  guides(fill = F) +
  colscale +
  facet_grid(param_P ~ param_R, labeller = label_both) +
  ggtitle("skewed (rare feature A), 23 cards")





plot_even_large <- outcomes_even_large %>% 
  pivot_longer( both_long:both_missing,
                names_to = "outcome",
                values_to = "count" ) %>% 
  mutate( outcome = fct_relevel(outcome,
                                "both_missing",
                                "B_missing",
                                "A_missing",
                                "both_short",
                                "only_B_long",
                                "only_A_long",
                                "both_long"
  )) %>% 
  ggplot(aes( x = param_E,
              y = count,
              fill = outcome )) +
  geom_area() +
  guides(fill = F) +
  colscale +
  facet_grid(param_P ~ param_R, labeller = label_both) +
  ggtitle("even pop., 24 cards")
## patchwork plot compositing:
(plot_even_small | plot_skewed_small) / (plot_even_large | plot_skewed_large)

## save as PDF:
plot_file_name <- paste0("plot/outcomes_",
                         Sys.Date() %>% str_replace_all("-", ""),
                         "_",
                         format(Sys.time(), "%X") %>% str_replace_all(":", ""),
                         "_N",
                         RUNS,
                         ".pdf")
ggsave(plot_file_name, width = 30, height = 15, units = "in")
```


ggsave("plots/outcomes_largepop.pdf")
```

