
```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(patchwork)

theme_set(theme_classic(base_size = 8) +
            theme(plot.background = element_rect(fill = NA, color = NA),
                  strip.background = element_rect(color = NA),
                  legend.background = element_rect(fill = NA)))

## load transcript data:
transcript <- read_excel("../data/arg2 transcript.xlsx")[-1,][1:297,] %>%
  select(
    subject,
    card_no,
    rare,
    slotA_filled,
    slotL_filled,
    current_arms,
    current_legs,
    move
  )

## load subject data:
subjects <- read_excel("../data/arg2 participants.xlsx") %>%
  select(
    subject,
    dob,
    date,
    condition,
    drop
  ) %>%
  mutate(
    subject = as.integer(subject),
    condition = as.factor(condition),
    dob = ymd(dob),
    date = ymd(date),
    age = as.numeric(date - dob) / 365.25,
    drop = as.logical(drop)
  ) %>%
  ## remove dropouts:
  filter(is.na(drop)) %>%
  select(-drop)

## load coding reference sheet:
states_actions <- read_excel("states and actions.xlsx",
                             range = "B3:L84") %>% 
  select(-`_`)
```

Evaluate each move in the transcript as to whether it violates relevance, risks losing a rare card, or squanders search cost.

```{r}
## create long form of lookup table for easy joining (= looking up), add
## 'alternatives' columns to evaluate whether an OK move was the alternative to
## a costly/irrelevant/risky move:
coding_table <- states_actions %>%
  pivot_longer(new:aL, names_to = "move", values_to = "evaluation") %>% 
  group_by(rare, slotA_filled, slotL_filled, current_arms, current_legs) %>% 
  mutate( alt_irrel = TRUE %in% str_detect(evaluation, "irrel"),
          alt_cost  = TRUE %in% str_detect(evaluation, "cost"),
          alt_Rcert = TRUE %in% str_detect(evaluation, "Rcert"),
          alt_Rposs = TRUE %in% str_detect(evaluation, "Rposs")) %>% 
  ungroup

## do evaluation - match each line of the transcript to the coding table, look
## up how the move is to be evatuated and what errors "were available":
transcript_evaluated <- transcript %>% 
  left_join(coding_table,
            by = c("rare", "slotA_filled", "slotL_filled", "current_arms", "current_legs", "move") )
```

Summarize each type of error and "omission of errors" for each participant.

```{r}
ptcp_scores <- transcript_evaluated %>% 
  group_by(subject) %>% 
  summarize( relevance_related = sum(alt_irrel),
             irrelevant        = sum(str_detect(evaluation, "irrel")),
             relevant          = relevance_related - irrelevant,
             ##
             cost_related = sum(alt_cost),
             cost_wasting = sum(str_detect(evaluation, "cost")),
             cost_saving  = cost_related - cost_wasting,
             ##
             risk_related  = sum(alt_Rcert) + sum(alt_Rposs),
             risk_insens   = sum(str_detect(evaluation, "R....")),
             risk_sens     = risk_related - risk_insens )
```

Join transcription codes with subject data.

```{r}
d <- subjects %>% 
  left_join(ptcp_scores, by = "subject") %>% 
  select( -c(dob, date) )
```


```{r}
plot_triptych <- d %>%
  select( -c(irrelevant, risk_insens, cost_wasting) ) %>% 
  pivot_longer( c(relevance_related:risk_sens) ) %>% 
  mutate(aspect = as.factor(name),
         name = NULL,
         aspect = fct_collapse( aspect,
                                relevance = c("relevance_related", "relevant"),
                                risk = c("risk_related", "risk_sens"),
                                cost = c("cost_related", "cost_saving") ),
         variable = rep(c("N", "count"), length.out = n() )) %>% 
  pivot_wider(names_from = variable, values_from = value)

head(plot_triptych)
```

```{r}
levels(plot_triptych$aspect) <- c("Cost-effectiveness", "Risk-avoidance", "Relevance-seeking")

gg_triptych <- ggplot(plot_triptych,
                      aes(x = age,
                          y = count / N,
                          size = N)) +
  geom_abline(intercept = .5, slope = 0, linetype = "8414", alpha = .3, size = 1) +
  geom_point(fill = "#d00a55",
             alpha = .3,
             shape = 21) +
  geom_point(color = "black",
             shape = 1) +
  #geom_rug(size = 1, sides = "b", color = "#d00a55") +
  scale_y_continuous(limits = c(0, 1)) +
  facet_grid(. ~ aspect) +
  labs(size = "No. of\ndecisions", x = "Age", y = "Proportion adaptive information choices") +
  theme(panel.background = element_rect(color = "grey70"))

ggsave(plot = gg_triptych, filename = "plots/cogsci_arg2.pdf", width = 18, height = 6, units = "cm", dpi = 600)
gg_triptych
```
